# Generated by Django 3.2.12 on 2022-04-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('hobby', models.CharField(choices=[('dance', 'Dance'), ('travel', 'Travelling'), ('reading', 'Reading'), ('art', 'Art')], max_length=20)),
            ],
        ),
    ]
