# Generated by Django 3.2.12 on 2022-04-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_rename_username_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='uname',
        ),
    ]
