# Generated by Django 3.2.12 on 2022-04-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20220427_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
